package io.cherrytechnologies.msscsagaexecutioncoordinator.domain;

public enum BeerOrderEvent {
    VALIDATE_ORDER, VALIDATION_SUCCESS, VALIDATION_FAILED,
    ALLOCATION_SUCCESS, ALLOCATION_FAILED, ALLOCATION_NO_INVENTORY,
    BEER_ORDER_PICKED_UP, DELIVERED, DELIVERY_EXCEPTION, CANCEL_ORDER
}
